import json

data = [
  {
    "integration_name": "asana-api",
    "official_site": "https://asana.com",
    "rpc_docs": "",
    "api_docs": "https://developers.asana.com/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Asana API allows developers to interact with workspaces, tasks, projects, and portfolios within the Asana work management platform."
  },
  {
    "integration_name": "jira-cloud",
    "official_site": "https://www.atlassian.com/software/jira",
    "rpc_docs": "",
    "api_docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Jira Cloud REST API enables programmatic interaction with Jira issues, workflows, and project structures."
  },
  {
    "integration_name": "confluence-cloud",
    "official_site": "https://www.atlassian.com/software/confluence",
    "rpc_docs": "",
    "api_docs": "https://developer.atlassian.com/cloud/confluence/rest/v1/intro/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Confluence Cloud API provides developers access to manage pages, spaces, contents, and user permissions."
  },
  {
    "integration_name": "bitbucket-cloud",
    "official_site": "https://bitbucket.org",
    "rpc_docs": "",
    "api_docs": "https://developer.atlassian.com/cloud/bitbucket/rest/intro/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Bitbucket Cloud REST API supports source code repository management, pull requests, and automation pipelines."
  },
  {
    "integration_name": "monday-api",
    "official_site": "https://monday.com",
    "rpc_docs": "",
    "api_docs": "https://developer.monday.com/api-reference/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Monday.com API utilizes a GraphQL structure to control boards, items, columns, and workspace details."
  },
  {
    "integration_name": "clickup-api",
    "official_site": "https://clickup.com",
    "rpc_docs": "",
    "api_docs": "https://clickup.com/api/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "ClickUp API enables building custom applications and tracking items across teams, spaces, and tasks."
  },
  {
    "integration_name": "linear-api",
    "official_site": "https://linear.app",
    "rpc_docs": "",
    "api_docs": "https://studio.linear.app/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Linear API provides a flexible GraphQL endpoint to query and mutate issues, teams, projects, and cycles."
  },
  {
    "integration_name": "notion-api",
    "official_site": "https://www.notion.so",
    "rpc_docs": "",
    "api_docs": "https://developers.notion.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Notion API connects workspaces to external tools, managing databases, blocks, and page structures."
  },
  {
    "integration_name": "coda-api",
    "official_site": "https://coda.io",
    "rpc_docs": "",
    "api_docs": "https://coda.io/developers/apis/v1",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Coda API allows developers to read, update, and manage structured collaborative documents and document tables."
  },
  {
    "integration_name": "slite",
    "official_site": "https://slite.com",
    "rpc_docs": "",
    "api_docs": "https://slite.com/developers",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Slite platform interfaces manage modern knowledge management systems and workspace document architectures."
  },
  {
    "integration_name": "loom",
    "official_site": "https://www.loom.com",
    "rpc_docs": "",
    "api_docs": "https://developers.loom.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Loom platform integration provides asymmetric video message creation and custom distribution tooling."
  },
  {
    "integration_name": "figma-api",
    "official_site": "https://www.figma.com",
    "rpc_docs": "",
    "api_docs": "https://www.figma.com/developers/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Figma API provides access to visual design files, version histories, and specific layout components."
  },
  {
    "integration_name": "miro-api",
    "official_site": "https://miro.com",
    "rpc_docs": "",
    "api_docs": "https://developers.miro.com/reference",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Miro API enables creating and editing widgets, boards, and interactive canvas components programmably."
  },
  {
    "integration_name": "whimsical",
    "official_site": "https://whimsical.com",
    "rpc_docs": "",
    "api_docs": "https://whimsical.com/developers",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Whimsical integration manages structural diagram creation and enterprise collaborative canvas tasks."
  },
  {
    "integration_name": "lucidchart",
    "official_site": "https://www.lucidchart.com",
    "rpc_docs": "",
    "api_docs": "https://developer.lucid.co",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Lucid platform API controls diagram layouts and structured enterprise data model generation mapping."
  },
  {
    "integration_name": "trello-api",
    "official_site": "https://trello.com",
    "rpc_docs": "",
    "api_docs": "https://developer.atlassian.com/cloud/trello/rest/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Trello REST API gives programmatic control over boards, lists, cards, and automation actions."
  },
  {
    "integration_name": "todoist",
    "official_site": "https://todoist.com",
    "rpc_docs": "",
    "api_docs": "https://developer.todoist.com/rest/v2/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Todoist REST API provides direct endpoints to manipulate operational task records, projects, and reminders."
  },
  {
    "integration_name": "evernote",
    "official_site": "https://evernote.com",
    "rpc_docs": "",
    "api_docs": "https://dev.evernote.com/doc/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Evernote developer interface utilizes Thrift definitions to create, index, and organize digital notes."
  },
  {
    "integration_name": "onenote",
    "official_site": "https://www.microsoft.com/en-us/microsoft-365/onenote/learning-tools",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/en-us/graph/api/resources/onenote",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "OneNote Graph integration structures cloud notebook partitions, note pages, and document sections."
  },
  {
    "integration_name": "google-keep",
    "official_site": "https://keep.google.com",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/keep/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Keep API enables enterprise administrators to monitor and manage user workspace note assets."
  },
  {
    "integration_name": "dropbox-api",
    "official_site": "https://www.dropbox.com",
    "rpc_docs": "",
    "api_docs": "https://www.dropbox.com/developers/documentation",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Dropbox API handles distributed binary file synchronization, directory creation, and access link sharing."
  },
  {
    "integration_name": "box-api",
    "official_site": "https://www.box.com",
    "rpc_docs": "",
    "api_docs": "https://developer.box.com/reference/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Box Content API supports secure file hosting, metadata management, and document metadata structures."
  },
  {
    "integration_name": "onedrive-api",
    "official_site": "https://onedrive.live.com",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/en-us/graph/api/resources/onedrive",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "OneDrive storage engine exposes file management and document tracking via the Microsoft Graph interface."
  },
  {
    "integration_name": "sharepoint-online",
    "official_site": "https://www.microsoft.com/en-us/microsoft-365/sharepoint/collaboration",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/en-us/sharepoint/dev/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "SharePoint Online developer services govern internal web content structures and corporate data libraries."
  },
  {
    "integration_name": "google-workspace",
    "official_site": "https://workspace.google.com",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/workspace",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Workspace APIs map core enterprise directory options and unified application settings."
  },
  {
    "integration_name": "google-sheets",
    "official_site": "https://sheets.google.com",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/sheets/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Sheets API automates spreadsheet cellular modifications, layout updates, and data formatting."
  },
  {
    "integration_name": "google-docs",
    "official_site": "https://docs.google.com",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/docs/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Docs API enables reading and structural modification of rich document document entities."
  },
  {
    "integration_name": "google-slides",
    "official_site": "https://slides.google.com",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/slides/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Slides API automates presentation layout changes, visual shapes generation, and text formatting."
  },
  {
    "integration_name": "google-forms",
    "official_site": "https://forms.google.com",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/forms/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Forms API controls interactive collection structures, question configurations, and responses tracking."
  },
  {
    "integration_name": "gmail-api",
    "official_site": "https://mail.google.com",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/gmail/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Gmail REST API provides access to user mailbox entities, message threads, labels, and draft templates."
  },
  {
    "integration_name": "outlook-mail",
    "official_site": "[suspicious link removed]",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/en-us/graph/api/resources/mail",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Outlook Mail interface implements message routing, indexing, and mailbox structure alterations."
  },
  {
    "integration_name": "outlook-calendar",
    "official_site": "[suspicious link removed]",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/en-us/graph/api/resources/calendar",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Outlook Calendar API coordinates booking items, group meetings, and schedule layouts."
  },
  {
    "integration_name": "exchange-online",
    "official_site": "https://www.microsoft.com/en-us/microsoft-365/exchange/email",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/ews-fluid-concepts",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Exchange Online integration handles enterprise message governance and administrative data routing."
  },
  {
    "integration_name": "teams-api",
    "official_site": "https://www.microsoft.com/en-us/microsoft-365/microsoft-teams",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/en-us/graph/api/resources/teams",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Microsoft Teams API governs chat messaging streams, operational channel layouts, and user group options."
  },
  {
    "integration_name": "zoom-api",
    "official_site": "https://zoom.us",
    "rpc_docs": "",
    "api_docs": "https://developers.zoom.us/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Zoom API handles continuous user webhooks, instance management, and meeting setup tasks."
  },
  {
    "integration_name": "webex",
    "official_site": "https://www.webex.com",
    "rpc_docs": "",
    "api_docs": "https://developer.webex.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cisco Webex API controls meeting endpoints, continuous video routing, and message layouts."
  },
  {
    "integration_name": "slack-enterprise",
    "official_site": "https://slack.com",
    "rpc_docs": "",
    "api_docs": "https://api.slack.com/enterprise",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Slack Enterprise API addresses large-scale multi-workspace security logging and structural channel deployment."
  },
  {
    "integration_name": "discord-api",
    "official_site": "[suspicious link removed]",
    "rpc_docs": "",
    "api_docs": "https://discord.com/developers/docs/intro",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Discord Developer API manages bot communication parameters, custom server configurations, and message objects."
  },
  {
    "integration_name": "telegram-bot",
    "official_site": "https://telegram.org",
    "rpc_docs": "",
    "api_docs": "https://core.telegram.org/bots/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Telegram Bot API utilizes an HTTP mechanism to execute chat automated bots and message actions."
  },
  {
    "integration_name": "whatsapp-business",
    "official_site": "https://www.whatsapp.com/business/",
    "rpc_docs": "",
    "api_docs": "https://developers.facebook.com/docs/whatsapp",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "WhatsApp Business Platform Cloud API implements conversational messaging flows for enterprise users."
  },
  {
    "integration_name": "signal-api",
    "official_site": "https://signal.org",
    "rpc_docs": "",
    "api_docs": "",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Signal communications platform manages secure end-to-end user encryption messaging paradigms."
  },
  {
    "integration_name": "twilio-voice",
    "official_site": "https://www.twilio.com",
    "rpc_docs": "",
    "api_docs": "https://www.twilio.com/docs/voice/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Twilio Programmable Voice API controls globally routed cloud phone calls and automated interactive response tracking."
  },
  {
    "integration_name": "twilio-sms",
    "official_site": "https://www.twilio.com",
    "rpc_docs": "",
    "api_docs": "https://www.twilio.com/docs/sms/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Twilio Programmable SMS API manages transactional global mobile message distribution and logging tasks."
  },
  {
    "integration_name": "vonage",
    "official_site": "https://www.vonage.com",
    "rpc_docs": "",
    "api_docs": "https://developer.vonage.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Vonage API suite orchestrates multi-channel business telephony, voice integrations, and text components."
  },
  {
    "integration_name": "plivo",
    "official_site": "https://www.plivo.com",
    "rpc_docs": "",
    "api_docs": "https://www.plivo.com/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Plivo platform interface manages text transport tasks and cloud communication system deployments."
  },
  {
    "integration_name": "telnyx",
    "official_site": "https://telnyx.com",
    "rpc_docs": "",
    "api_docs": "https://developers.telnyx.com/docs/api/v2/overview",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Telnyx API controls connectivity layers, phone records discovery, and messaging routing paradigms."
  },
  {
    "integration_name": "sendinblue",
    "official_site": "https://www.brevo.com",
    "rpc_docs": "",
    "api_docs": "https://developers.brevo.com/reference",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Brevo (formerly Sendinblue) REST API handles marketing message routing, automated contact sorting, and status parameters."
  },
  {
    "integration_name": "mailjet",
    "official_site": "https://www.mailjet.com",
    "rpc_docs": "",
    "api_docs": "https://dev.mailjet.com/email/reference/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Mailjet API manages high-volume transactional emails and marketing message layout analytics."
  },
  {
    "integration_name": "postmark-api",
    "official_site": "https://postmarkapp.com",
    "rpc_docs": "",
    "api_docs": "https://postmarkapp.com/developer",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Postmark Developer API ensures high-reliability delivery tracking for transactional application emails."
  },
  {
    "integration_name": "mailgun-api",
    "official_site": "https://www.mailgun.com",
    "rpc_docs": "",
    "api_docs": "https://documentation.mailgun.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Mailgun API exposes cloud tracking engines for automated outbound email distributions."
  },
  {
    "integration_name": "sparkpost",
    "official_site": "https://www.sparkpost.com",
    "rpc_docs": "",
    "api_docs": "https://developers.sparkpost.com/api/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "SparkPost API manages enterprise programmatic analytics and fast email generation layers."
  },
  {
    "integration_name": "aws-ses",
    "official_site": "https://aws.amazon.com/ses/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/ses/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Simple Email Service handles scalable text messaging loops and marketing verification tasks."
  },
  {
    "integration_name": "aws-sns",
    "official_site": "https://aws.amazon.com/sns/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/sns/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Simple Notification Service manages high-throughput pub/sub system components."
  },
  {
    "integration_name": "aws-sqs",
    "official_site": "https://aws.amazon.com/sqs/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/sqs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Simple Queue Service provisions distributed message queue structures for decoupled microservices."
  },
  {
    "integration_name": "aws-lambda",
    "official_site": "https://aws.amazon.com/lambda/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/lambda/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Lambda handles execution routines for on-demand event-driven serverless code blocks."
  },
  {
    "integration_name": "aws-ec2",
    "official_site": "https://aws.amazon.com/ec2/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/ec2/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Elastic Compute Cloud structures virtual computing environments and on-demand compute infrastructure resource groups."
  },
  {
    "integration_name": "aws-s3",
    "official_site": "https://aws.amazon.com/s3/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/s3/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Simple Storage Service provides cloud object storage parameters and static binary data management."
  },
  {
    "integration_name": "aws-eks",
    "official_site": "https://aws.amazon.com/eks/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/eks/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Elastic Kubernetes Service hosts managed control plane layers for running standard container cluster deployments."
  },
  {
    "integration_name": "aws-ecs",
    "official_site": "https://aws.amazon.com/ecs/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/ecs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Elastic Container Service automates container runtime scaling tasks and microservice task groups."
  },
  {
    "integration_name": "aws-batch",
    "official_site": "https://aws.amazon.com/batch/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/batch/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Batch schedules high-volume technical computing routines across multi-node infrastructure nodes."
  },
  {
    "integration_name": "aws-athena",
    "official_site": "https://aws.amazon.com/athena/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/athena/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Athena queries structured layout records stored inside file storage layers using standard SQL syntax."
  },
  {
    "integration_name": "aws-glue",
    "official_site": "https://aws.amazon.com/glue/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/glue/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Glue handles automated serverless server components for data transformation pipelines and data tracing."
  },
  {
    "integration_name": "aws-redshift",
    "official_site": "https://aws.amazon.com/redshift/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/redshift/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Redshift controls enterprise-grade database arrays optimized for analytical tracking suites."
  },
  {
    "integration_name": "aws-dynamodb",
    "official_site": "https://aws.amazon.com/dynamodb/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/dynamodb/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon DynamoDB manages schema-free structural document storage layouts with low retrieval latencies."
  },
  {
    "integration_name": "aws-rds",
    "official_site": "https://aws.amazon.com/rds/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/rds/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Relational Database Service handles administrative cloud hosting configurations for SQL data clusters."
  },
  {
    "integration_name": "aws-opensearch",
    "official_site": "https://aws.amazon.com/opensearch-service/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/opensearch-service/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon OpenSearch Service provisions managed instances for real-time document search indexing tasks."
  },
  {
    "integration_name": "aws-kinesis",
    "official_site": "https://aws.amazon.com/kinesis/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/kinesis/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Kinesis collects and monitors real-time streaming data sequences across decoupled messaging loops."
  },
  {
    "integration_name": "aws-emr",
    "official_site": "https://aws.amazon.com/emr/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/emr/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Elastic MapReduce coordinates large-scale big data cluster deployments using frameworks like Spark and Hadoop."
  },
  {
    "integration_name": "aws-bedrock-inference",
    "official_site": "https://aws.amazon.com/bedrock/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/bedrock/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Bedrock manages execution parameters and configuration pathways to interact with foundation language models."
  },
  {
    "integration_name": "azure-functions",
    "official_site": "https://azure.microsoft.com/services/functions/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/azure-functions/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Functions allows building event-driven serverless code scripts inside managed cloud clusters."
  },
  {
    "integration_name": "azure-vm",
    "official_site": "https://azure.microsoft.com/services/virtual-machines/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/virtual-machines/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Virtual Machines provide on-demand hypervisor container hosting infrastructures and computing nodes."
  },
  {
    "integration_name": "azure-storage",
    "official_site": "https://azure.microsoft.com/services/storage/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/storage/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Storage engine handles blob storage parameters, distributed structured file tables, and data volumes."
  },
  {
    "integration_name": "azure-cosmosdb",
    "official_site": "https://azure.microsoft.com/services/cosmos-db/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/cosmos-db/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Cosmos DB offers highly distributed multi-model document storage layouts with global failover tracing."
  },
  {
    "integration_name": "azure-sql",
    "official_site": "https://azure.microsoft.com/services/azure-sql/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/azure-sql/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure SQL Database platform implements fully managed relational database architectures."
  },
  {
    "integration_name": "azure-kubernetes",
    "official_site": "https://azure.microsoft.com/services/kubernetes-service/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/aks/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Kubernetes Service simplifies multi-node container execution management and infrastructure orchestration."
  },
  {
    "integration_name": "azure-eventhub",
    "official_site": "https://azure.microsoft.com/services/event-hubs/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/event-hubs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Event Hubs provides high-volume transactional data ingestion layers for real-time telemetry analytics."
  },
  {
    "integration_name": "azure-servicebus",
    "official_site": "https://azure.microsoft.com/services/service-bus/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/service-bus-messaging/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Service Bus maintains reliable asynchronous cloud messaging cues and multi-tenant transaction buffers."
  },
  {
    "integration_name": "azure-ml",
    "official_site": "https://azure.microsoft.com/services/machine-learning/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/azure/machine-learning/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Azure Machine Learning platform automates technical model training, runtime validation, and container model deployments."
  },
  {
    "integration_name": "gcp-compute",
    "official_site": "https://cloud.google.com/compute",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/compute/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Compute Engine allocates virtual server machines running across internal infrastructure arrays."
  },
  {
    "integration_name": "gcp-storage",
    "official_site": "https://cloud.google.com/storage",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/storage/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Cloud Storage delivers unified object storage blocks for hosting big unstructured payloads."
  },
  {
    "integration_name": "gcp-bigquery",
    "official_site": "https://cloud.google.com/bigquery",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/bigquery/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google BigQuery manages petabyte-scale serverless data warehousing configurations for analytical searching tasks."
  },
  {
    "integration_name": "gcp-pubsub",
    "official_site": "https://cloud.google.com/pubsub",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/pubsub/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Cloud Pub/Sub implements real-time messaging buses for connecting decoupled computing scripts."
  },
  {
    "integration_name": "gcp-cloudrun",
    "official_site": "https://cloud.google.com/run",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/run/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Cloud Run runs serverless frontend and backend containerized stacks via simple HTTP invocation pathways."
  },
  {
    "integration_name": "gcp-cloudfunctions",
    "official_site": "https://cloud.google.com/functions",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/functions/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Cloud Functions provides lightweight serverless computational environments triggered by platform microservices."
  },
  {
    "integration_name": "gcp-vertexai",
    "official_site": "https://cloud.google.com/vertex-ai",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/vertex-ai/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Vertex AI manages machine learning pipelines, baseline model tuning parameters, and model hosting gateways."
  },
  {
    "integration_name": "digitalocean",
    "official_site": "https://www.digitalocean.com",
    "rpc_docs": "",
    "api_docs": "https://docs.digitalocean.com/reference/api/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "DigitalOcean API automates Droplet infrastructure lifecycle tasks, network layout provisioning, and container space blocks."
  },
  {
    "integration_name": "linode",
    "official_site": "https://www.linode.com",
    "rpc_docs": "",
    "api_docs": "https://techdocs.akamai.com/linode-api/reference/api-summary",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Linode API (Akamai Cloud Computing) controls virtual hardware compute instances and cloud load balancer configurations."
  },
  {
    "integration_name": "vultr",
    "official_site": "https://www.vultr.com",
    "rpc_docs": "",
    "api_docs": "https://www.vultr.com/api/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Vultr API provisions cloud host processing layers, storage networks, and bare-metal technical deployment arrays."
  },
  {
    "integration_name": "ovhcloud",
    "official_site": "https://www.ovhcloud.com",
    "rpc_docs": "",
    "api_docs": "https://api.ovh.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "OVHcloud API manages technical storage architectures, virtual network routing instances, and bare metal nodes."
  },
  {
    "integration_name": "hetzner",
    "official_site": "https://www.hetzner.com",
    "rpc_docs": "",
    "api_docs": "https://docs.hetzner.cloud",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Hetzner Cloud API supports automated deployment of Linux virtual instances and storage volume extensions."
  },
  {
    "integration_name": "scaleway",
    "official_site": "https://www.scaleway.com",
    "rpc_docs": "",
    "api_docs": "https://developers.scaleway.com/en/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Scaleway Developer API controls multi-tenant compute nodes, storage buckets, and load balancer setups."
  },
  {
    "integration_name": "upcloud",
    "official_site": "https://upcloud.com",
    "rpc_docs": "",
    "api_docs": "https://developers.upcloud.com/1.3/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "UpCloud API provisions fast cloud storage allocations and managed operating system compute profiles."
  },
  {
    "integration_name": "render-cloud",
    "official_site": "https://render.com",
    "rpc_docs": "",
    "api_docs": "https://api-docs.render.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Render API automates application environment scaling parameters and static site generation pipelines."
  },
  {
    "integration_name": "flyio-machines",
    "official_site": "https://fly.io",
    "rpc_docs": "",
    "api_docs": "https://fly.io/docs/machines/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Fly.io Machines API launches microVM instances inside global edge processing targets."
  },
  {
    "integration_name": "cloudflare-workers",
    "official_site": "https://workers.cloudflare.com",
    "rpc_docs": "",
    "api_docs": "https://developers.cloudflare.com/workers/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloudflare Workers platforms support serverless execution configurations directly across edge networking targets."
  },
  {
    "integration_name": "cloudflare-d1",
    "official_site": "https://www.cloudflare.com",
    "rpc_docs": "",
    "api_docs": "https://developers.cloudflare.com/d1/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloudflare D1 runs client relational database parameters using SQLite routing setups located at edge targets."
  },
  {
    "integration_name": "cloudflare-kv",
    "official_site": "https://www.cloudflare.com",
    "rpc_docs": "",
    "api_docs": "https://developers.cloudflare.com/kv/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloudflare Workers KV provides low-latency edge key-value storage access rules."
  },
  {
    "integration_name": "cloudflare-r2",
    "official_site": "https://www.cloudflare.com",
    "rpc_docs": "",
    "api_docs": "https://developers.cloudflare.com/r2/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloudflare R2 implements egress-fee-free object storage nodes compatible with the Amazon S3 standard."
  },
  {
    "integration_name": "cloudflare-stream",
    "official_site": "https://www.cloudflare.com",
    "rpc_docs": "",
    "api_docs": "https://developers.cloudflare.com/stream/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloudflare Stream aggregates video encoding workflows and global media layout caching paths."
  },
  {
    "integration_name": "fastly",
    "official_site": "https://www.fastly.com",
    "rpc_docs": "",
    "api_docs": "https://developer.fastly.com/reference/api/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Fastly API configures edge cache validation rules, content delivery parameters, and edge computing layers."
  },
  {
    "integration_name": "akamai",
    "official_site": "https://www.akamai.com",
    "rpc_docs": "",
    "api_docs": "https://techdocs.akamai.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Akamai Developer Tools configure enterprise content optimization setups and global safety rule groups."
  },
  {
    "integration_name": "vercel-edge",
    "official_site": "https://vercel.com",
    "rpc_docs": "",
    "api_docs": "https://vercel.com/docs/functions/edge-functions",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Vercel Edge Functions execute V8 computing runtime scripts inside low-latency edge nodes."
  },
  {
    "integration_name": "netlify-functions",
    "official_site": "https://www.netlify.com",
    "rpc_docs": "",
    "api_docs": "https://docs.netlify.com/functions/overview/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Netlify Functions manage serverless backend routing tasks linked directly to structural codebase automation rules."
  },
  {
    "integration_name": "supabase-auth",
    "official_site": "https://supabase.com",
    "rpc_docs": "",
    "api_docs": "https://supabase.com/docs/guides/auth",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Supabase Auth components structure identity token validation pathways and OAuth protocol links."
  },
  {
    "integration_name": "supabase-db",
    "official_site": "https://supabase.com",
    "rpc_docs": "",
    "api_docs": "https://supabase.com/docs/guides/database",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Supabase Database infrastructure maps relational data storage setups using PostgreSQL data clusters."
  },
  {
    "integration_name": "supabase-storage",
    "official_site": "https://supabase.com",
    "rpc_docs": "",
    "api_docs": "https://supabase.com/docs/guides/storage",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Supabase Storage systems track user media content structures and binary asset downloads."
  },
  {
    "integration_name": "firebase-auth",
    "official_site": "https://firebase.google.com",
    "rpc_docs": "",
    "api_docs": "https://firebase.google.com/docs/auth",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Firebase Authentication maps client identity validations and multi-tenant token flows."
  },
  {
    "integration_name": "firebase-firestore",
    "official_site": "https://firebase.google.com",
    "rpc_docs": "",
    "api_docs": "https://firebase.google.com/docs/firestore",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloud Firestore provides real-time document-based storage models for client setups."
  },
  {
    "integration_name": "firebase-realtime-db",
    "official_site": "https://firebase.google.com",
    "rpc_docs": "",
    "api_docs": "https://firebase.google.com/docs/database",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Firebase Realtime Database handles live transactional JSON data mapping across computing nodes."
  },
  {
    "integration_name": "firebase-functions",
    "official_site": "https://firebase.google.com",
    "rpc_docs": "",
    "api_docs": "https://firebase.google.com/docs/functions",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloud Functions for Firebase executes serverless backend processing instances via explicit application events."
  },
  {
    "integration_name": "firebase-hosting",
    "official_site": "https://firebase.google.com",
    "rpc_docs": "",
    "api_docs": "https://firebase.google.com/docs/hosting",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Firebase Hosting structures fast web content delivery paths for assets and client routing setups."
  },
  {
    "integration_name": "mongodb-atlas",
    "official_site": "https://www.mongodb.com/cloud/atlas",
    "rpc_docs": "",
    "api_docs": "https://www.mongodb.com/docs/atlas/api/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "MongoDB Atlas Admin API automates managed cloud database configuration tasks and data tracking."
  },
  {
    "integration_name": "couchbase",
    "official_site": "https://www.couchbase.com",
    "rpc_docs": "",
    "api_docs": "https://docs.couchbase.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Couchbase API controls scalable NoSQL storage environments and structured memory indexes."
  },
  {
    "integration_name": "cassandra",
    "official_site": "https://cassandra.apache.org",
    "rpc_docs": "",
    "api_docs": "https://cassandra.apache.org/doc/latest/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Apache Cassandra governs highly scalable, fault-tolerant distributed column-family storage engines."
  },
  {
    "integration_name": "scylla",
    "official_site": "https://www.scylladb.com",
    "rpc_docs": "",
    "api_docs": "https://docs.scylladb.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "ScyllaDB delivers high-throughput NoSQL database setups built on a C++ architectural model."
  },
  {
    "integration_name": "timescaledb",
    "official_site": "https://www.timescale.com",
    "rpc_docs": "",
    "api_docs": "https://docs.timescale.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "TimescaleDB optimizes PostgreSQL database engines specifically for time-series data storage."
  },
  {
    "integration_name": "influxdb",
    "official_site": "https://www.influxdata.com",
    "rpc_docs": "",
    "api_docs": "https://docs.influxdata.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "InfluxDB API interacts with specialized time-series storage nodes and query logging suites."
  },
  {
    "integration_name": "questdb",
    "official_site": "https://questdb.io",
    "rpc_docs": "",
    "api_docs": "https://questdb.io/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "QuestDB uses SQL paradigms to execute fast ingestion and tracking of timestamped sequences."
  },
  {
    "integration_name": "clickhouse",
    "official_site": "https://clickhouse.com",
    "rpc_docs": "",
    "api_docs": "https://clickhouse.com/docs/en/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "ClickHouse implements columnar relational storage formats optimized for real-time analytical reporting."
  },
  {
    "integration_name": "snowflake-api",
    "official_site": "https://www.snowflake.com",
    "rpc_docs": "",
    "api_docs": "https://docs.snowflake.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Snowflake SQL API enables programmatic query execution across enterprise data warehouse systems."
  },
  {
    "integration_name": "databricks-api",
    "official_site": "https://www.databricks.com",
    "rpc_docs": "",
    "api_docs": "https://docs.databricks.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Databricks REST API automates big data lakehouse workspace provisioning and computation cluster lifecycles."
  },
  {
    "integration_name": "bigquery-storage",
    "official_site": "https://cloud.google.com/bigquery",
    "rpc_docs": "",
    "api_docs": "https://cloud.google.com/bigquery/docs/reference/storage",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "BigQuery Storage API uses gRPC protocols to execute fast, high-volume streaming data downloads from BigQuery clusters."
  },
  {
    "integration_name": "redshift-serverless",
    "official_site": "https://aws.amazon.com/redshift/",
    "rpc_docs": "",
    "api_docs": "https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-headline.html",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Amazon Redshift Serverless handles elastic data warehouse query runs without computing instance maintenance."
  },
  {
    "integration_name": "postgres-cloud",
    "official_site": "https://www.postgresql.org",
    "rpc_docs": "",
    "api_docs": "https://www.postgresql.org/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "PostgreSQL core structures define advanced SQL standard relational databasing layers."
  },
  {
    "integration_name": "mysql-cloud",
    "official_site": "https://www.mysql.com",
    "rpc_docs": "",
    "api_docs": "https://dev.mysql.com/doc/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "MySQL network implementations manage structural data sorting loops and client tracking parameters."
  },
  {
    "integration_name": "neo4j",
    "official_site": "https://neo4j.com",
    "rpc_docs": "",
    "api_docs": "https://neo4j.com/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Neo4j database engine structures deep graph-relation tracking models using the Cypher syntax."
  },
  {
    "integration_name": "dgraph",
    "official_site": "https://dgraph.io",
    "rpc_docs": "",
    "api_docs": "https://dgraph.io/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Dgraph scales native transactional graph data models via standardized GraphQL integration pathways."
  },
  {
    "integration_name": "arangodb",
    "official_site": "https://www.arangodb.com",
    "rpc_docs": "",
    "api_docs": "https://www.arangodb.com/docs/stable/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "ArangoDB API implements unified document, key-value, and graph multi-model storage configurations."
  },
  {
    "integration_name": "elastic-cloud",
    "official_site": "https://www.elastic.co",
    "rpc_docs": "",
    "api_docs": "https://www.elastic.co/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Elastic Cloud API manages hosted Elasticsearch instances, index mappings, and analytical processing parameters."
  },
  {
    "integration_name": "logz",
    "official_site": "https://logz.io",
    "rpc_docs": "",
    "api_docs": "https://docs.logz.io",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Logz.io provides cloud analytics environments targeting system security monitoring logs."
  },
  {
    "integration_name": "sumologic",
    "official_site": "https://www.sumologic.com",
    "rpc_docs": "",
    "api_docs": "https://help.sumologic.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Sumo Logic API controls log data ingestion and security data tracking components."
  },
  {
    "integration_name": "splunk-cloud",
    "official_site": "https://www.splunk.com",
    "rpc_docs": "",
    "api_docs": "https://docs.splunk.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Splunk Cloud API governs programmatic search index interactions and corporate metrics pipeline management."
  },
  {
    "integration_name": "honeycomb",
    "official_site": "https://www.honeycomb.io",
    "rpc_docs": "",
    "api_docs": "https://docs.honeycomb.io",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Honeycomb API accepts structural telemetry events to evaluate system performance and software trace patterns."
  },
  {
    "integration_name": "lightstep",
    "official_site": "https://lightstep.com",
    "rpc_docs": "",
    "api_docs": "https://docs.lightstep.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Lightstep (ServiceNow Cloud Observability) analyzes massive distributed application trace data metrics."
  },
  {
    "integration_name": "grafana-enterprise",
    "official_site": "https://grafana.com",
    "rpc_docs": "",
    "api_docs": "https://grafana.com/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Grafana Enterprise HTTP API automates data source settings, visualization dashboard layouts, and user group roles."
  },
  {
    "integration_name": "prometheus-remote",
    "official_site": "https://prometheus.io",
    "rpc_docs": "",
    "api_docs": "https://prometheus.io/docs/prometheus/latest/storage/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Prometheus Remote Write protocol forwards technical metric time-series arrays onto long-term storage platforms."
  },
  {
    "integration_name": "tempo-cloud",
    "official_site": "https://grafana.com/oss/tempo/",
    "rpc_docs": "",
    "api_docs": "https://grafana.com/docs/tempo/latest/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Grafana Tempo coordinates massive distributed object tracking indices for backend microservices."
  },
  {
    "integration_name": "loki-cloud",
    "official_site": "https://grafana.com/oss/loki/",
    "rpc_docs": "",
    "api_docs": "https://grafana.com/docs/loki/latest/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Grafana Loki implements index-free log aggregation systems optimized for Prometheus metadata mapping."
  },
  {
    "integration_name": "jaeger-cloud",
    "official_site": "https://www.jaegertracing.io",
    "rpc_docs": "",
    "api_docs": "https://www.jaegertracing.io/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Jaeger tracing infrastructure collects and visualizes microservice transactional execution pathways."
  },
  {
    "integration_name": "opentelemetry-collector",
    "official_site": "https://opentelemetry.io",
    "rpc_docs": "",
    "api_docs": "https://opentelemetry.io/docs/collector/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "OpenTelemetry Collector manages proxy components that process, filter, and export tracking data logs."
  },
  {
    "integration_name": "snyk",
    "official_site": "https://snyk.io",
    "rpc_docs": "",
    "api_docs": "https://docs.snyk.io",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Snyk API tracks open-source dependency vulnerabilities and container structural risk definitions."
  },
  {
    "integration_name": "veracode",
    "official_site": "https://www.veracode.com",
    "rpc_docs": "",
    "api_docs": "https://docs.veracode.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Veracode platform API manages code static analytics scans and application safety testing parameters."
  },
  {
    "integration_name": "checkmarx",
    "official_site": "https://checkmarx.com",
    "rpc_docs": "",
    "api_docs": "https://checkmarx.com/resource/documentation/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Checkmarx components handle vulnerability lifecycle discovery and software compilation scanning tasks."
  },
  {
    "integration_name": "sonarqube",
    "official_site": "https://www.sonarqube.org",
    "rpc_docs": "",
    "api_docs": "https://docs.sonarqube.org",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "SonarQube Web API checks structural code metrics, test tracking volumes, and continuous bugs parameters."
  },
  {
    "integration_name": "dependabot",
    "official_site": "https://github.com/dependabot",
    "rpc_docs": "",
    "api_docs": "https://docs.github.com/code-security/dependabot",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Dependabot engine automates out-of-date package scanning tasks and repository upgrade requests."
  },
  {
    "integration_name": "github-actions",
    "official_site": "https://github.com",
    "rpc_docs": "",
    "api_docs": "https://docs.github.com/actions",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "GitHub Actions workflow engines automate code building pipelines and testing environments."
  },
  {
    "integration_name": "gitlab-ci",
    "about.gitlab.com": "https://about.gitlab.com",
    "rpc_docs": "",
    "api_docs": "https://docs.gitlab.com/ee/ci/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "GitLab CI infrastructure maps code compilation runners and validation lifecycle jobs."
  },
  {
    "integration_name": "circleci",
    "official_site": "https://circleci.com",
    "rpc_docs": "",
    "api_docs": "https://circleci.com/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "CircleCI API monitors automation pipeline parameters and software orchestration workflows."
  },
  {
    "integration_name": "travisci",
    "official_site": "https://www.travis-ci.com",
    "rpc_docs": "",
    "api_docs": "https://docs.travis-ci.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Travis CI API manages continuous engineering builds and environmental pipeline logs."
  },
  {
    "integration_name": "jenkins",
    "official_site": "https://www.jenkins.io",
    "rpc_docs": "",
    "api_docs": "https://www.jenkins.io/doc/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Jenkins automation server exposes remote APIs to invoke test loops and check pipeline instances."
  },
  {
    "integration_name": "argo-workflows",
    "official_site": "https://argoproj.github.io/workflows/",
    "rpc_docs": "",
    "api_docs": "https://argoproj.github.io/argo-workflows/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Argo Workflows schedules containerized step loops natively on top of Kubernetes platforms."
  },
  {
    "integration_name": "argo-events",
    "official_site": "https://argoproj.github.io/events/",
    "rpc_docs": "",
    "api_docs": "https://argoproj.github.io/argo-events/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Argo Events delivers declarative event-driven processing structures for Kubernetes runtime states."
  },
  {
    "integration_name": "tekton",
    "official_site": "https://tekton.dev",
    "rpc_docs": "",
    "api_docs": "https://tekton.dev/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Tekton architecture specifies cloud-native software pipeline design building blocks."
  },
  {
    "integration_name": "hashicorp-vault",
    "official_site": "https://www.vaultproject.io",
    "rpc_docs": "",
    "api_docs": "https://developer.hashicorp.com/vault/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "HashiCorp Vault controls cryptographic token tracking, application credential storage, and transit keys."
  },
  {
    "integration_name": "hashicorp-consul",
    "official_site": "https://www.consul.io",
    "rpc_docs": "",
    "api_docs": "https://developer.hashicorp.com/consul/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "HashiCorp Consul delivers network mesh discovery setups and localized service configuration registries."
  },
  {
    "integration_name": "hashicorp-nomad",
    "official_site": "https://www.nomadproject.io",
    "rpc_docs": "",
    "api_docs": "https://developer.hashicorp.com/nomad/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "HashiCorp Nomad manages flexible workload scheduling loops across raw container profiles."
  },
  {
    "integration_name": "terraform-cloud",
    "official_site": "https://www.terraform.io",
    "rpc_docs": "",
    "api_docs": "https://developer.hashicorp.com/terraform/cloud-docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Terraform Cloud API drives infrastructure-as-code run states and environmental variable state configurations."
  },
  {
    "integration_name": "pulumi-cloud",
    "official_site": "https://www.pulumi.com",
    "rpc_docs": "",
    "api_docs": "https://www.pulumi.com/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Pulumi Cloud API handles deployment tracking parameters for programmatic code infrastructure frameworks."
  },
  {
    "integration_name": "ansible-automation",
    "official_site": "https://www.ansible.com",
    "rpc_docs": "",
    "api_docs": "https://docs.ansible.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Ansible platform environments automate remote task execution routines via playbook scripts."
  },
  {
    "integration_name": "chef-automate",
    "official_site": "https://www.chef.io",
    "rpc_docs": "",
    "api_docs": "https://docs.chef.io/automate/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Chef Automate offers centralized monitoring frameworks checking server cluster configurations."
  },
  {
    "integration_name": "pagerduty",
    "official_site": "https://www.pagerduty.com",
    "rpc_docs": "",
    "api_docs": "https://developer.pagerduty.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "PagerDuty REST API configures rotation schedules, incident alerts routing, and notification triggers."
  },
  {
    "integration_name": "opsgenie",
    "official_site": "https://www.atlassian.com/software/opsgenie",
    "rpc_docs": "",
    "api_docs": "https://support.atlassian.com/opsgenie/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Opsgenie REST API processes system alert models and coordinates developer team call loops."
  },
  {
    "integration_name": "victorops",
    "official_site": "https://www.splunk.com/en_us/products/splunko11y/victorops.html",
    "rpc_docs": "",
    "api_docs": "https://docs.splunk.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "VictorOps (Splunk On-Call) manages infrastructure incident dispatch targets and status tracking loops."
  },
  {
    "integration_name": "statuspage",
    "official_site": "https://www.statuspage.io",
    "rpc_docs": "",
    "api_docs": "https://developer.statuspage.io",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Statuspage API updates infrastructure outage parameters and customer downtime notifications."
  },
  {
    "integration_name": "freshservice",
    "official_site": "https://freshservice.com",
    "rpc_docs": "",
    "api_docs": "https://api.freshservice.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Freshservice API manages IT asset ticket queues, internal change records, and service components."
  },
  {
    "integration_name": "servicenow",
    "official_site": "https://www.servicenow.com",
    "rpc_docs": "",
    "api_docs": "https://developer.servicenow.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "ServiceNow REST APIs drive enterprise workflow data matrices and system configuration mapping."
  },
  {
    "integration_name": "zendesk-support",
    "official_site": "https://www.zendesk.com",
    "rpc_docs": "",
    "api_docs": "https://developer.zendesk.com/api-reference/ticketing/introduction/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Zendesk Support API structures customer conversation tickets, user profiles, and view configurations."
  },
  {
    "integration_name": "zendesk-chat",
    "official_site": "https://www.zendesk.com",
    "rpc_docs": "",
    "api_docs": "https://developer.zendesk.com/api-reference/live-chat/introduction/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Zendesk Chat routing rules control live agent communication channels and session metrics logs."
  },
  {
    "integration_name": "intercom-api",
    "official_site": "https://www.intercom.com",
    "rpc_docs": "",
    "api_docs": "https://developers.intercom.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Intercom API manages behavioral user messaging feeds, helpdesk conversations, and customer identity indices."
  },
  {
    "integration_name": "helpscout",
    "official_site": "https://www.helpscout.com",
    "rpc_docs": "",
    "api_docs": "https://developer.helpscout.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Help Scout REST API drives shared team mailbox structures and support contact profiles."
  },
  {
    "integration_name": "frontapp",
    "official_site": "https://front.com",
    "rpc_docs": "",
    "api_docs": "https://dev.frontapp.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Front API handles collaborative customer inbox models and communication channel data tracking."
  },
  {
    "integration_name": "hubspot-crm",
    "official_site": "https://www.hubspot.com",
    "rpc_docs": "",
    "api_docs": "https://developers.hubspot.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "HubSpot CRM APIs orchestrate contact tracking arrays, business company properties, and deal progress states."
  },
  {
    "integration_name": "hubspot-marketing",
    "official_site": "https://www.hubspot.com",
    "rpc_docs": "",
    "api_docs": "https://developers.hubspot.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "HubSpot Marketing platform interfaces update email campaigns, form configurations, and target landing list records."
  },
  {
    "integration_name": "salesforce-crm",
    "official_site": "https://www.salesforce.com",
    "rpc_docs": "",
    "api_docs": "https://developer.salesforce.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Salesforce REST API controls extensive business transaction objects and relational client properties."
  },
  {
    "integration_name": "salesforce-marketing",
    "official_site": "https://www.salesforce.com",
    "rpc_docs": "",
    "api_docs": "https://developer.salesforce.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Salesforce Marketing Cloud APIs handle dynamic messaging tracks and behavioral target group data models."
  },
  {
    "integration_name": "pipedrive-api",
    "official_site": "https://www.pipedrive.com",
    "rpc_docs": "",
    "api_docs": "https://developers.pipedrive.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Pipedrive API updates transaction pipeline definitions, target deals tracking, and activity tasks profiles."
  },
  {
    "integration_name": "zoho-crm",
    "official_site": "https://www.zoho.com/crm/",
    "rpc_docs": "",
    "api_docs": "https://www.zoho.com/crm/developer/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Zoho CRM REST API governs business modules properties, lead collection queues, and account histories tracking."
  },
  {
    "integration_name": "close-com",
    "official_site": "https://close.com",
    "rpc_docs": "",
    "api_docs": "[suspicious link removed]",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Close API exposes lead profile fields, automated outbound phone calls metadata, and status events loops."
  },
  {
    "integration_name": "copper-crm",
    "official_site": "https://www.copper.com",
    "rpc_docs": "",
    "api_docs": "https://developer.copper.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Copper API manages workspace properties structured around standard Google Workspace communication tracks."
  },
  {
    "integration_name": "keap",
    "official_site": "https://keap.com",
    "rpc_docs": "",
    "api_docs": "https://developer.keap.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Keap REST API drives CRM contact profiles and automated payment parameters."
  },
  {
    "integration_name": "freshsales",
    "official_site": "https://www.freshworks.com/freshsales-crm/",
    "rpc_docs": "",
    "api_docs": "https://developer.freshsales.io",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Freshsales API orchestrates customer connection records and corporate sales pipeline states."
  },
  {
    "integration_name": "bigin",
    "official_site": "https://www.bigin.com",
    "rpc_docs": "",
    "api_docs": "https://www.zoho.com/bigin/developer/docs/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Bigin API maps simple transaction tracking models tailored for lightweight team structures."
  },
  {
    "integration_name": "stripe-billing",
    "official_site": "https://stripe.com",
    "rpc_docs": "",
    "api_docs": "https://docs.stripe.com/billing",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Stripe Billing API automates recurring usage tracking parameters, customer invoice flows, and code scripts configurations."
  },
  {
    "integration_name": "stripe-issuing",
    "official_site": "https://stripe.com",
    "rpc_docs": "",
    "api_docs": "https://docs.stripe.com/issuing",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Stripe Issuing controls dynamic commercial card rendering workflows and digital asset validation."
  },
  {
    "integration_name": "stripe-treasury",
    "official_site": "https://stripe.com",
    "rpc_docs": "",
    "api_docs": "https://docs.stripe.com/treasury",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Stripe Treasury provides financial ledger configurations to build scalable money transit modules."
  },
  {
    "integration_name": "paypal-payouts",
    "official_site": "https://www.paypal.com",
    "rpc_docs": "",
    "api_docs": "https://developer.paypal.com/docs/payouts/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "PayPal Payouts API handles high-volume global balance distributions onto individual user accounts."
  },
  {
    "integration_name": "square-terminal",
    "official_site": "https://squareup.com",
    "rpc_docs": "",
    "api_docs": "https://developer.squareup.com/reference/square/terminal-api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Square Terminal API routes transactional checkouts straight down onto hardware point-of-sale stations."
  },
  {
    "integration_name": "square-online",
    "official_site": "https://squareup.com",
    "rpc_docs": "",
    "api_docs": "https://developer.squareup.com/docs/square-online-api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Square Online integrations manage web storefront inventories and ecommerce item data layouts."
  },
  {
    "integration_name": "adyen-checkout",
    "official_site": "https://www.adyen.com",
    "rpc_docs": "",
    "api_docs": "https://docs.adyen.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Adyen Checkout API handles localized banking gateways and multi-currency commercial charge networks."
  },
  {
    "integration_name": "checkout-payments",
    "official_site": "https://www.checkout.com",
    "rpc_docs": "",
    "api_docs": "https://docs.checkout.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Checkout.com Payments API accepts structural transaction events to clear multi-tenant global commerce records."
  },
  {
    "integration_name": "wise-business",
    "official_site": "https://wise.com/business/",
    "rpc_docs": "",
    "api_docs": "https://api-docs.wise.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Wise Business API automates cross-border settlement loops and commercial treasury distribution rails."
  },
  {
    "integration_name": "airwallex-api",
    "official_site": "https://www.airwallex.com",
    "rpc_docs": "",
    "api_docs": "https://www.airwallex.com/docs/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Airwallex API governs digital corporate bank vault creations and fast international money conversions."
  },
  {
    "integration_name": "marqeta",
    "official_site": "https://www.marqeta.com",
    "rpc_docs": "",
    "api_docs": "https://www.marqeta.com/docs/developers",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Marqeta Core API provides modern card issuing solutions and programmatic payment authorization loops."
  },
  {
    "integration_name": "synapsefi",
    "official_site": "https://synapsefi.com",
    "rpc_docs": "",
    "api_docs": "",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Synapse platform provides historical compliance tracking architectures and banking ledger configurations."
  },
  {
    "integration_name": "unit-finance",
    "official_site": "https://www.unit.co",
    "rpc_docs": "",
    "api_docs": "https://docs.unit.co",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Unit Banking-as-a-Service API governs digital token vault creations, accounting ledgers, and transaction loops."
  },
  {
    "integration_name": "ramp-api",
    "official_site": "https://ramp.com",
    "rpc_docs": "",
    "api_docs": "https://docs.ramp.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Ramp API manages enterprise expense tracking rows, corporate statement processing paths, and limit setups."
  },
  {
    "integration_name": "brex-api",
    "official_site": "https://www.brex.com",
    "rpc_docs": "",
    "api_docs": "https://developer.brex.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Brex Developer API structures commercial user cash limits and corporate transactional ledger tracking."
  },
  {
    "integration_name": "plaid-transactions",
    "official_site": "https://plaid.com",
    "rpc_docs": "",
    "api_docs": "https://plaid.com/docs/transactions/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Plaid Transactions API fetches sanitized ledger tracking variables straight out from verified customer bank profiles."
  },
  {
    "integration_name": "teller-api",
    "official_site": "https://teller.io",
    "rpc_docs": "",
    "api_docs": "https://teller.io/docs",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Teller Bank Integration core handles high-fidelity direct connection endpoints tracking checking accounts information."
  },
  {
    "integration_name": "finicity-api",
    "official_site": "https://www.finicity.com",
    "rpc_docs": "",
    "api_docs": "https://developer.finicity.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Mastercard Finicity API provisions open banking aggregation tools and structural credit data verification layers."
  },
  {
    "integration_name": "truework-api",
    "official_site": "https://www.truework.com",
    "rpc_docs": "",
    "api_docs": "https://developers.truework.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Truework API structures identity tracking parameters to run automated income validation steps."
  },
  {
    "integration_name": "persona-idv",
    "official_site": "https://withpersona.com",
    "rpc_docs": "",
    "api_docs": "https://docs.withpersona.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Persona IDV components handle automated user verification flows and customer document risk processing."
  },
  {
    "integration_name": "onfido-idv",
    "official_site": "https://onfido.com",
    "rpc_docs": "",
    "api_docs": "https://documentation.onfido.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Onfido API maps digital identity validation tests and international KYC compliance loops."
  },
  {
    "integration_name": "trulioo",
    "official_site": "https://www.trulioo.com",
    "rpc_docs": "",
    "api_docs": "https://developer.trulioo.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Trulioo Global Gateway API performs real-time international user business profile evaluations."
  },
  {
    "integration_name": "jumio",
    "official_site": "https://www.jumio.com",
    "rpc_docs": "",
    "api_docs": "https://www.jumio.com/documentation/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Jumio Verification platform interfaces analyze biometrics images and user passport identity structures."
  },
  {
    "integration_name": "auth0-enterprise",
    "official_site": "https://auth0.com",
    "rpc_docs": "",
    "api_docs": "https://auth0.com/docs/api",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Auth0 Enterprise Management API updates corporate identity pools, SSO profiles, and permission logs."
  },
  {
    "integration_name": "okta-identity",
    "official_site": "https://www.okta.com",
    "rpc_docs": "",
    "api_docs": "https://developer.okta.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Okta Identity API governs enterprise access token verification structures and single sign-on parameters."
  },
  {
    "integration_name": "azure-ad",
    "official_site": "https://learn.microsoft.com/azure/active-directory/",
    "rpc_docs": "",
    "api_docs": "https://learn.microsoft.com/graph/azure-ad-overview",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Microsoft Entra ID (formerly Azure AD) endpoints monitor group configurations and directory access tokens."
  },
  {
    "integration_name": "google-identity",
    "official_site": "https://developers.google.com/identity",
    "rpc_docs": "",
    "api_docs": "https://developers.google.com/identity/protocols/oauth2",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Google Identity Services manage secure open standard token authorization tracks and verification pathways."
  },
  {
    "integration_name": "duo-security",
    "official_site": "https://duo.com",
    "rpc_docs": "",
    "api_docs": "https://duo.com/docs/duomobile",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Duo Security Admin API manages multi-factor validation logs and edge enrollment steps."
  },
  {
    "integration_name": "cloudflare-zero-trust",
    "official_site": "https://www.cloudflare.com/zero-trust/",
    "rpc_docs": "",
    "api_docs": "https://developers.cloudflare.com/cloudflare-one/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Cloudflare Access gates enforce strict identity conditions across distributed proxy routing targets."
  },
  {
    "integration_name": "tailscale",
    "official_site": "https://tailscale.com",
    "rpc_docs": "",
    "api_docs": "https://tailscale.com/api/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Tailscale REST API controls virtual private mesh profiles and overlay interface keys."
  },
  {
    "integration_name": "zerotier",
    "official_site": "https://www.zerotier.com",
    "rpc_docs": "",
    "api_docs": "https://docs.zerotier.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "ZeroTier Central API handles virtual cloud link paths and node authorizations."
  },
  {
    "integration_name": "1password",
    "official_site": "https://1password.com",
    "rpc_docs": "",
    "api_docs": "https://developer.1password.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "1Password Developer Tools deploy local secret manager daemons to feed secure runtime variables."
  },
  {
    "integration_name": "lastpass",
    "official_site": "https://www.lastpass.com",
    "rpc_docs": "",
    "api_docs": "https://support.lastpass.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "LastPass Enterprise implementations manage centralized corporate key directories."
  },
  {
    "integration_name": "bitwarden",
    "official_site": "https://bitwarden.com",
    "rpc_docs": "",
    "api_docs": "https://bitwarden.com/help/",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Bitwarden Secrets CLI manages open-source container security configurations and token values."
  },
  {
    "integration_name": "keeper",
    "official_site": "https://www.keepersecurity.com",
    "rpc_docs": "",
    "api_docs": "https://docs.keepersecurity.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Keeper Security SDK drives enterprise cryptographic storage profiles and access audits."
  },
  {
    "integration_name": "dashlane",
    "official_site": "https://www.dashlane.com",
    "rpc_docs": "",
    "api_docs": "https://developers.dashlane.com",
    "sdk_repos": [],
    "openapi_specs": [],
    "health_check_endpoints": [],
    "logo_url": "",
    "usage_examples": [],
    "notes": "Dashlane Business environments manage administrative vault parameters and token governance laws."
  }
]

print(json.dumps(data, indent=2))
