"use client";

import React from "react";

export default function AffiliateEngineSection() {
    return (
        <section id="affiliate-engine" className="py-24 bg-black text-white relative border-t border-slate-900 overflow-hidden">
            {/* Ambient Purple/Indigo Glow */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-purple-600/15 rounded-full blur-[140px] pointer-events-none" />

            <div className="max-w-5xl mx-auto px-4 md:px-8 relative z-10">
                <div className="bg-gradient-to-b from-slate-950 via-slate-900/90 to-slate-950 border border-purple-500/30 rounded-3xl p-8 md:p-14 backdrop-blur-2xl shadow-2xl space-y-10 text-center">
                    
                    {/* Header */}
                    <div className="space-y-4 max-w-3xl mx-auto">
                        <span className="inline-block text-xs font-mono font-bold text-purple-400 uppercase tracking-widest bg-purple-950/80 border border-purple-800/60 px-3.5 py-1.5 rounded-full">
                            Viral Affiliate &amp; Growth Engine
                        </span>

                        <h2 className="text-3xl md:text-5xl font-extrabold tracking-tight font-space-grotesk uppercase leading-tight text-white">
                            Scale Your Earnings: <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 via-pink-300 to-indigo-400">Build a Community Fleet</span>
                        </h2>

                        <p className="text-slate-300 text-base md:text-lg leading-relaxed">
                            Every device connected makes the world less dependent on dirty mega-datacenters. Share your personal invite link with friends, family, or your online audience and build a recurring revenue stream:
                        </p>
                    </div>

                    {/* Revenue Breakdown Grid: 2x2 on md+ */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-left">
                        {/* 70% Operator Share Panel */}
                        <div className="bg-emerald-950/40 border border-emerald-500/50 p-5 rounded-2xl flex items-start gap-4 hover:border-emerald-400/70 transition-all shadow-[0_0_20px_rgba(16,185,129,0.15)]">
                            <div className="text-2xl p-2.5 bg-emerald-500/20 rounded-xl text-emerald-400 font-bold font-mono">70%</div>
                            <div className="space-y-1">
                                <div className="flex items-center gap-2 flex-wrap">
                                    <h4 className="text-white font-bold text-base font-space-grotesk">70% Operator Revenue Share</h4>
                                    <span className="text-[10px] font-mono font-semibold text-emerald-300 bg-emerald-900/80 border border-emerald-700/60 px-2 py-0.5 rounded-full uppercase">Primary Payout</span>
                                </div>
                                <p className="text-xs text-slate-300 leading-relaxed">The node operator retains 70% of all gross compute revenue generated by their connected hardware.</p>
                            </div>
                        </div>

                        {/* 10% Sales Source */}
                        <div className="bg-slate-900/80 border border-amber-500/30 p-5 rounded-2xl flex items-start gap-4 hover:border-amber-400/50 transition-all space-y-1">
                            <div className="text-2xl p-2.5 bg-amber-500/20 rounded-xl text-amber-400 font-bold font-mono">10%</div>
                            <div>
                                <h4 className="text-white font-bold text-base font-space-grotesk">10% Sales Source Commission</h4>
                                <p className="text-xs text-slate-300 leading-relaxed">Permanent commission on compute demand you originate for the network.</p>
                            </div>
                        </div>

                        {/* 3% Level 1 Direct */}
                        <div className="bg-slate-900/80 border border-blue-500/30 p-5 rounded-2xl flex items-start gap-4 hover:border-blue-400/50 transition-all space-y-1">
                            <div className="text-2xl p-2.5 bg-blue-500/20 rounded-xl text-blue-400 font-bold font-mono">3%</div>
                            <div>
                                <h4 className="text-white font-bold text-base font-space-grotesk">3% Level 1 Direct Override</h4>
                                <p className="text-xs text-slate-300 leading-relaxed">Earned on every active node operator you personally invite.</p>
                            </div>
                        </div>

                        {/* 7% Level 2 Network */}
                        <div className="bg-slate-900/80 border border-purple-500/30 p-5 rounded-2xl flex items-start gap-4 hover:border-purple-400/50 transition-all space-y-1">
                            <div className="text-2xl p-2.5 bg-purple-500/20 rounded-xl text-purple-400 font-bold font-mono">7%</div>
                            <div>
                                <h4 className="text-white font-bold text-base font-space-grotesk">7% Level 2 Network Override</h4>
                                <p className="text-xs text-slate-300 leading-relaxed">Compounding returns when your referrals bring in their own circles.</p>
                            </div>
                        </div>
                    </div>

                    {/* Guarantee Note */}
                    <p className="text-xs font-mono text-purple-300 bg-purple-950/50 border border-purple-900/60 p-4 rounded-xl max-w-3xl mx-auto leading-relaxed">
                        No inventory, no upfront packages, and no recruitment tricks. Pure, compliant revenue-sharing powered by real-world computing demand.
                    </p>

                    {/* CTA Button Underneath */}
                    <div className="pt-2">
                        <a
                            href="https://nodlr.wnode.one"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-2 bg-gradient-to-r from-purple-600 via-pink-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold text-sm uppercase px-10 py-4.5 rounded-xl transition-all shadow-[0_0_35px_rgba(147,51,234,0.4)] hover:shadow-[0_0_50px_rgba(147,51,234,0.6)] transform hover:-translate-y-0.5"
                        >
                            Get Referral Link &rarr;
                        </a>
                    </div>

                </div>
            </div>
        </section>
    );
}
