"use client";

import React from "react";
import Callout from "@/components/docs/Callout";

export default function AffiliateGuidePage() {
  return (
    <div className="max-w-4xl space-y-10 py-8 text-white">
      {/* Page Header */}
      <div>
        <div className="text-xs font-mono font-bold tracking-widest text-emerald-400 uppercase mb-2 bg-emerald-950/60 border border-emerald-800/50 px-3 py-1 rounded-full inline-block">
          Help &amp; Operational Guide
        </div>
        <h1 className="text-3xl md:text-5xl font-black text-white tracking-tight font-space-grotesk uppercase mt-1">
          Operator &amp; Affiliate Payments Guide
        </h1>
        <p className="mt-3 text-base md:text-lg text-slate-300 leading-relaxed">
          A plain-English guide to understanding your daily compute earnings, referral overrides, and automated cash payouts straight to your bank account.
        </p>
      </div>

      <Callout type="note" title="Canon Payment Rule">
        Wnode operates on a <strong>70% direct operator revenue share</strong> model. Every device running Node Operator receives 70% of gross compute fees generated, with daily automatic cash payouts via Stripe Connect.
      </Callout>

      {/* Visual Diagram Banner */}
      <div className="rounded-2xl border border-purple-500/30 bg-slate-950 p-6 md:p-8 space-y-4 shadow-2xl relative overflow-hidden">
        <div className="flex items-center justify-between">
          <span className="text-xs font-mono font-bold uppercase tracking-widest text-purple-400">
            Protocol Payout Flow Diagram
          </span>
          <span className="text-xs font-mono text-emerald-400 bg-emerald-950/80 border border-emerald-800/60 px-2.5 py-1 rounded-md">
            Daily Cash Payouts Active
          </span>
        </div>

        <figure className="my-4 rounded-xl border border-slate-800 bg-black/60 p-4">
          <img 
            src="/diagrams/affiliate_depin_engine_diagram.png" 
            alt="Affiliate & DePIN Compute Revenue Flow Diagram" 
            className="w-full h-auto max-h-[380px] object-contain rounded-lg mx-auto"
          />
          <figcaption className="mt-3 text-center text-xs text-slate-400">
            Figure 1.1 – Real-time revenue routing from AI compute buyers to Node Operators &amp; Affiliate fleet builders.
          </figcaption>
        </figure>
      </div>

      {/* 4 Revenue Breakdown Cards */}
      <section className="space-y-6">
        <h2 className="text-2xl font-bold font-space-grotesk text-white border-b border-slate-800 pb-3">
          1. Revenue Share &amp; Commission Matrix
        </h2>
        <p className="text-slate-300 text-sm leading-relaxed">
          Revenue generated by the Wnode network is distributed deterministically across hardware operators and community builders without hidden fees:
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
          {/* 70% Hardware Owner */}
          <div className="bg-emerald-950/40 border border-emerald-500/50 p-5 rounded-2xl flex items-start gap-4 shadow-[0_0_20px_rgba(16,185,129,0.15)]">
            <div className="text-2xl p-2.5 bg-emerald-500/20 rounded-xl text-emerald-400 font-bold font-mono">70%</div>
            <div className="space-y-1">
              <h3 className="text-white font-bold text-base font-space-grotesk">Node Operator Share</h3>
              <p className="text-xs text-slate-300 leading-relaxed">Retained directly by hardware owners running lightweight background compute jobs.</p>
            </div>
          </div>

          {/* 10% Sales Source */}
          <div className="bg-slate-900/80 border border-amber-500/30 p-5 rounded-2xl flex items-start gap-4">
            <div className="text-2xl p-2.5 bg-amber-500/20 rounded-xl text-amber-400 font-bold font-mono">10%</div>
            <div className="space-y-1">
              <h3 className="text-white font-bold text-base font-space-grotesk">Sales Source Commission</h3>
              <p className="text-xs text-slate-300 leading-relaxed">Permanent recurring payout to the partner or link owner who originated the client demand.</p>
            </div>
          </div>

          {/* 3% Level 1 Direct */}
          <div className="bg-slate-900/80 border border-blue-500/30 p-5 rounded-2xl flex items-start gap-4">
            <div className="text-2xl p-2.5 bg-blue-500/20 rounded-xl text-blue-400 font-bold font-mono">3%</div>
            <div className="space-y-1">
              <h3 className="text-white font-bold text-base font-space-grotesk">Level 1 Direct Override</h3>
              <p className="text-xs text-slate-300 leading-relaxed">Earned on every active node operator you personally invite to connect devices.</p>
            </div>
          </div>

          {/* 7% Level 2 Network */}
          <div className="bg-slate-900/80 border border-purple-500/30 p-5 rounded-2xl flex items-start gap-4">
            <div className="text-2xl p-2.5 bg-purple-500/20 rounded-xl text-purple-400 font-bold font-mono">7%</div>
            <div className="space-y-1">
              <h3 className="text-white font-bold text-base font-space-grotesk">Level 2 Network Override</h3>
              <p className="text-xs text-slate-300 leading-relaxed">Compounding override when your direct referrals invite their own node circles.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Step-by-Step How It Works Section */}
      <section className="space-y-6">
        <h2 className="text-2xl font-bold font-space-grotesk text-white border-b border-slate-800 pb-3">
          2. How Payouts Work: Step-by-Step
        </h2>

        <div className="space-y-4">
          <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col md:flex-row items-start gap-5">
            <div className="w-10 h-10 rounded-full bg-blue-500/20 text-blue-400 font-bold text-lg flex items-center justify-center shrink-0 border border-blue-500/40">
              1
            </div>
            <div className="space-y-1">
              <h3 className="text-white font-bold text-base font-space-grotesk">Install &amp; Run Node Operator</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Download the lightweight Node Operator application on your spare laptop, mini PC, or home server. The node runs securely in RAM-only mode with zero SSD wear.
              </p>
            </div>
          </div>

          <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col md:flex-row items-start gap-5">
            <div className="w-10 h-10 rounded-full bg-purple-500/20 text-purple-400 font-bold text-lg flex items-center justify-center shrink-0 border border-purple-500/40">
              2
            </div>
            <div className="space-y-1">
              <h3 className="text-white font-bold text-base font-space-grotesk">Connect Bank or Stripe Account</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                In the Nodlr app or dashboard, navigate to <strong>Settings &rarr; Payouts</strong> and link your bank account via Stripe Connect. No crypto wallet or complex gas fees required.
              </p>
            </div>
          </div>

          <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-col md:flex-row items-start gap-5">
            <div className="w-10 h-10 rounded-full bg-emerald-500/20 text-emerald-400 font-bold text-lg flex items-center justify-center shrink-0 border border-emerald-500/40">
              3
            </div>
            <div className="space-y-1">
              <h3 className="text-white font-bold text-base font-space-grotesk">Receive Daily Automatic Cash Payouts</h3>
              <p className="text-xs text-slate-300 leading-relaxed">
                Every night at 00:00 UTC, your 70% compute share and referral overrides are calculated and transferred directly to your bank account once the $10 minimum threshold is met.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Frequently Asked Questions */}
      <section className="space-y-6">
        <h2 className="text-2xl font-bold font-space-grotesk text-white border-b border-slate-800 pb-3">
          3. Frequently Asked Questions
        </h2>

        <div className="space-y-4 text-xs">
          <div className="p-5 rounded-2xl bg-slate-900/50 border border-slate-800 space-y-2">
            <h4 className="text-sm font-bold text-white font-space-grotesk">Are there any hidden fees or deductions from my 70% share?</h4>
            <p className="text-slate-300 leading-relaxed">
              No. Your 70% operator share is net of protocol routing. Standard payment processor fees (Stripe) apply at cash payout, but Wnode takes zero additional cuts.
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-slate-900/50 border border-slate-800 space-y-2">
            <h4 className="text-sm font-bold text-white font-space-grotesk">How do I get my personal referral link?</h4>
            <p className="text-slate-300 leading-relaxed">
              Log into your Nodlr dashboard at <a href="https://nodlr.wnode.one" target="_blank" rel="noopener noreferrer" className="text-purple-400 hover:underline">nodlr.wnode.one</a> and copy your unique invite code under the <strong>Affiliates</strong> tab.
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-slate-900/50 border border-slate-800 space-y-2">
            <h4 className="text-sm font-bold text-white font-space-grotesk">Can I run multiple nodes on the same home network?</h4>
            <p className="text-slate-300 leading-relaxed">
              Yes! You can connect multiple laptops, mini PCs, or desktops. Each node earns independently based on its available RAM and CPU performance.
            </p>
          </div>
        </div>
      </section>

      {/* CTA Box */}
      <div className="p-8 rounded-3xl bg-gradient-to-r from-purple-900/40 via-slate-900 to-indigo-900/40 border border-purple-500/40 text-center space-y-4">
        <h3 className="text-xl font-bold font-space-grotesk text-white uppercase">
          Ready to Start Earning Daily Compute Income?
        </h3>
        <p className="text-xs text-slate-300 max-w-xl mx-auto">
          Download Node Operator in under 3 clicks, link your payout account, and start earning immediately.
        </p>
        <div className="pt-2">
          <a 
            href="https://nodlr.wnode.one" 
            target="_blank" 
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold text-xs uppercase px-8 py-3.5 rounded-xl transition-all shadow-[0_0_25px_rgba(147,51,234,0.4)]"
          >
            Claim Early Beta Access &rarr;
          </a>
        </div>
      </div>
    </div>
  );
}
